language: ruby
sudo: false
bundler_args: --binstubs sbin --standalone --without documentation debug
script: sbin/rspec
rvm:
  - 2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
